language: php
sudo: false

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache

## PHP versions we test against
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

## Build matrix for lowest and highest possible targets
matrix:
  allow_failures:
  - php: nightly
  include:
    - php: 5.4
      env: dependencies=lowest
    - php: 5.5
      env: dependencies=lowest
    - php: 5.6
      env: dependencies=lowest
    - php: 7.0
      env: dependencies=lowest
    - php: 7.1
      env: dependencies=lowest
    - php: hhvm
      env: dependencies=lowest
    - php: nightly
      env: dependencies=lowest
    - php: 5.4
      env: dependencies=highest
    - php: 5.5
      env: dependencies=highest
    - php: 5.6
      env: dependencies=highest
    - php: 7.0
      env: dependencies=highest
    - php: 7.1
      env: dependencies=highest
    - php: hhvm
      env: dependencies=highest
    - php: nightly
      env: dependencies=highest

## Update composer and run the appropriate composer command
before_script:
  - composer self-update
  - if [ -z "$dependencies" ]; then composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
  - if [ "$dependencies" = "highest" ]; then composer update -n; fi;
  - composer show -i

## Run the actual test
script: make travis

## Gather coverage and set it to coverage servers
after_script: make travis-after-script
